In [5]:
from pandas_datareader import data

In [10]:
import fix_yahoo_finance

In [12]:
fix_yahoo_finance.pdr_override()

In [13]:
chart_data = data.get_data_yahoo('005930.KS', #코스피:KS, 코스닥:KQ
                                '2016-01-01',
                                '2017-12-31'
                                )

[*********************100%***********************]  1 of 1 downloaded

In [15]:
import pandas as pd

In [17]:
df = pd.DataFrame(data=chart_data)

In [33]:
fileName = 'yahoo_stock_data'

In [34]:
df.to_csv(fileName, sep='\t', encoding='utf-8')

In [35]:
data = pd.read_csv(fileName, sep='\t', encoding='utf-8')

In [36]:
data

           Date     Open     High      Low    Close     Adj Close    Volume
0    2016-01-04  25200.0  25200.0  24100.0  24100.0   1177.206421  15346950
1    2016-01-05  24040.0  24360.0  23720.0  24160.0   1180.137085  10800100
2    2016-01-06  24160.0  24160.0  23360.0  23500.0   1147.898071  18337600
3    2016-01-07  23320.0  23660.0  23020.0  23260.0   1136.175049  14119400
4    2016-01-08  23260.0  23720.0  23260.0  23420.0   1143.990356  12888150
5    2016-01-11  23120.0  23320.0  22920.0  23040.0   1125.428833  12063850
6    2016-01-12  22960.0  23320.0  22880.0  22920.0   1119.567139  10314150
7    2016-01-13  23060.0  23180.0  22960.0  22960.0   1121.520996   7165800
8    2016-01-14  22620.0  22840.0  22620.0  22760.0   1111.751709  10451100
9    2016-01-15  22800.0  23040.0  22480.0  22640.0   1105.890015  10473200
10   2016-01-18  21760.0  22660.0  21760.0  22520.0   1100.028442  16010700
11   2016-01-19  22560.0  23420.0  22560.0  23420.0   1143.990356  10362100
12   2016-01-20  23200.0  23200.0  22640.0  22760.0   1111.751709   8352600
13   2016-01-21  22660.0  23100.0  22500.0  22620.0   1104.912964   9517600
14   2016-01-22  22900.0  23360.0  22900.0  23360.0   1141.059692   7376400
15   2016-01-25  23440.0  23520.0  23120.0  23240.0   1135.198120   7995650
16   2016-01-26  23100.0  23140.0  22720.0  22740.0   1110.774658   7619950
17   2016-01-27  22520.0  23500.0  22520.0  23500.0   1147.898071  13811850
18   2016-01-28  23280.0  23360.0  22780.0  22900.0   1118.590210  15795600
19   2016-01-29  22800.0  23000.0  22320.0  23000.0   1123.474976  21849150
20   2016-02-01  23040.0  23260.0  23020.0  23260.0   1136.175049  12998950
21   2016-02-02  23220.0  23320.0  22940.0  23120.0   1129.336426   8317400
22   2016-02-03  23000.0  23040.0  22740.0  22920.0   1119.567139   8725350
23   2016-02-04  23000.0  23220.0  22960.0  23120.0   1129.336426  12397950
24   2016-02-05  23120.0  23380.0  23120.0  23280.0   1137.151855   9404700
25   2016-02-11  22360.0  22740.0  22360.0  22600.0   1103.936279  15263100
26   2016-02-12  22600.0  23020.0  22440.0  22600.0   1103.936279  12811600
27   2016-02-15  23080.0  23200.0  22880.0  23080.0   1127.382568   9157300
28   2016-02-16  23160.0  23580.0  23140.0  23360.0   1141.059692   9020050
29   2016-02-17  23580.0  24020.0  23380.0  23700.0   1157.667603  12303100
..          ...      ...      ...      ...      ...           ...       ...
457  2017-11-15  55920.0  56320.0  55320.0  55340.0  19369.478516   8816950
458  2017-11-16  55440.0  56000.0  55400.0  55780.0  19523.482422   7640700
459  2017-11-17  56400.0  56880.0  55820.0  55820.0  19537.482422  10733150
460  2017-11-20  55900.0  55980.0  55200.0  55200.0  19320.478516   9472750
461  2017-11-21  55400.0  55840.0  55280.0  55280.0  19348.478516  10324700
462  2017-11-22  55980.0  56200.0  55620.0  55960.0  19586.484375   7952950
463  2017-11-23  55960.0  55980.0  55020.0  55300.0  19355.480469   6272900
464  2017-11-24  55300.0  55500.0  55180.0  55460.0  19411.480469   4536200
465  2017-11-27  55360.0  55360.0  52640.0  52640.0  18424.457031  18128900
466  2017-11-28  52700.0  53280.0  51720.0  53280.0  18648.462891  13499400
467  2017-11-29  53200.0  53240.0  52500.0  52600.0  18410.455078   9590250
468  2017-11-30  50800.0  51860.0  50200.0  50800.0  17780.439453  29634150
469  2017-12-01  50800.0  51780.0  50800.0  50840.0  17794.441406  12868600
470  2017-12-04  50840.0  51340.0  50020.0  51340.0  17969.445313  14865050
471  2017-12-05  50600.0  51300.0  50280.0  51260.0  17941.443359   9326550
472  2017-12-06  51260.0  51560.0  50020.0  50020.0  17507.433594  10889200
473  2017-12-07  50040.0  50980.0  50020.0  50740.0  17759.439453  11065600
474  2017-12-08  51360.0  52000.0  51040.0  52000.0  18200.451172  11290450
475  2017-12-11  52000.0  52040.0  51500.0  51780.0  18123.449219   8125850
476  2017-12-12  51820.0  52100.0  51660.0  52100.0  18235.451172   8765050
477  2017-12-13  52100.0  52100.0  51100.0  51320.0  17962.445313  11333700
478  2017-12-14  51320.0  52280.0  51060.0  51060.0  17871.441406  20310400
479  2017-12-15  51240.0  51480.0  50520.0  50620.0  17717.439453  14928550
480  2017-12-18  50620.0  51240.0  50620.0  51200.0  17920.443359   7350250
481  2017-12-19  51540.0  52080.0  51520.0  51560.0  18046.445313  11978600
482  2017-12-21  51000.0  51060.0  49100.0  49140.0  17199.425781  15624300
483  2017-12-22  49400.0  49960.0  49240.0  49700.0  17395.429688  11199650
484  2017-12-26  49760.0  50100.0  48200.0  48200.0  16870.417969  16039850
485  2017-12-27  48960.0  49560.0  48460.0  49360.0  31188.158203  10743600
486  2017-12-28  49560.0  50960.0  49500.0  50960.0  32199.119141   8985450

[487 rows x 7 columns]